// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/createPath": {
            "post": {
                "description": "allows you to create a new path if you are an admin",
                "consumes": [
                    "application/json"
                ],
                "summary": "Create new career path",
                "parameters": [
                    {
                        "description": "Complete the json to create new path",
                        "name": "body-json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Path has been created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "could not create Path",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "get the email and password to access",
                "consumes": [
                    "application/json"
                ],
                "summary": "Enter the system",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Allows to complete the json for login",
                        "name": "body-json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Login",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid login",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "invalid login",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/modifyPassword": {
            "put": {
                "description": "get the user and password update",
                "summary": "Modify user password",
                "parameters": [
                    {
                        "description": "Allows to replace the password for login",
                        "name": "New-password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "something went wrong with the given data or couldn't update password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "something went wrong with the given data or couldn't update password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "Invalid Password Update",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/passwordRecovery": {
            "put": {
                "description": "send email at the person what forgot the password",
                "produces": [
                    "application/json"
                ],
                "summary": "recovery the password if dont remember",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid email, please write your email or the given email is not registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "invalid email, please write your email or the given email is not registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error processing password recovery",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "ask for email and password for register in the app",
                "produces": [
                    "application/json"
                ],
                "summary": "creates the user register in the db",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User credentials",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "profilePhoto",
                        "name": "profilePhoto",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "surname",
                        "name": "surname",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user successfully registered",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "something went wrong with the given data, error or the given email is already in use",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "something went wrong with the given data, error or the given email is already in use",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error in register",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/userpath": {
            "get": {
                "description": "get user careerpath",
                "consumes": [
                    "application/json"
                ],
                "summary": "shows a complete original career path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status ok",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "missing id parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error occurred looking for the path",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
