// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "get user careerpath",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "shows a given user career path",
                "responses": {
                    "200": {
                        "description": "success show careerpath",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "missing id parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error occurred looking the path",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "Error show user path ",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/passwordRecovery": {
            "post": {
                "description": "send email at the person what forgot the password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "summary": "recovery the password if dont remember",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid email, please write your email or the given email is not registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "invalid email, please write your email or the given email is not registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error processing password recovery",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "get": {
                "description": "ask for email and password for register in the app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "creates the user register in the db",
                "responses": {
                    "200": {
                        "description": "user successfully registered",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "jwtKey"
                            }
                        }
                    },
                    "400": {
                        "description": "something went wrong with the given data, error or the given email is already in use",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "something went wrong with the given data, error or the given email is already in use",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "default": {
                        "description": "error in register",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
