basePath: /
host: localhost:8080
info:
  contact:
    email: careerpath.avalith@gmail.com
    name: Career Path API Support
    url: http://www.swagger.io/support
  description: This is an application that allows you to manage your career path
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Career Path API
  version: "1.0"
paths: {}
swagger: "2.0"
