info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get the email and password to access
      produces:
      - application/json
      responses:
        "200":
          description: Success Login
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: invalid login
          schema:
            type: string
        "404":
          description: invalid login
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: Enter the system
  /passwordRecovery:
    post:
      consumes:
      - application/json
      description: send email at the person what forgot the password
      produces:
      - text/html
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: invalid email, please write your email or the given email is
            not registered
          schema:
            type: string
        "404":
          description: invalid email, please write your email or the given email is
            not registered
          schema:
            type: string
        default:
          description: error processing password recovery
          schema:
            type: string
      summary: recovery the password if dont remember
  /register:
    get:
      consumes:
      - application/json
      description: ask for email and password for register in the app
      produces:
      - application/json
      responses:
        "200":
          description: user successfully registered
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: something went wrong with the given data, error or the given
            email is already in use
          schema:
            type: string
        "404":
          description: something went wrong with the given data, error or the given
            email is already in use
          schema:
            type: string
        default:
          description: error in register
          schema:
            type: string
      summary: creates the user register in the db
swagger: "2.0"
