info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get the email and password to access
      operationId: login
      parameters:
      - description: Allows to complete the json for login
        in: body
        name: body-json
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Success Login
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: invalid login
          schema:
            type: string
        "404":
          description: invalid login
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: Enter the system
  /modifyPassword:
    put:
      description: get the user and password update
      parameters:
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: JWT Token
        in: query
        name: token
        required: true
        type: string
      - description: New Pass
        in: query
        name: newpass
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Password updated
          schema:
            type: string
        "400":
          description: something went wrong with the given data or couldn't update
            password
          schema:
            type: string
        "404":
          description: something went wrong with the given data or couldn't update
            password
          schema:
            type: string
        default:
          description: Invalid Password Update
          schema:
            type: string
      summary: Modify user password
  /passwordRecovery:
    put:
      description: send email at the person what forgot the password
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: invalid email, please write your email or the given email is
            not registered
          schema:
            type: string
        "404":
          description: invalid email, please write your email or the given email is
            not registered
          schema:
            type: string
        default:
          description: error processing password recovery
          schema:
            type: string
      summary: recovery the password if dont remember
  /register:
    post:
      description: ask for email and password for register in the app
      parameters:
      - description: User credentials
        in: formData
        name: name
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: profilePhoto
        in: formData
        name: profilePhoto
        required: true
        type: file
      - description: surname
        in: formData
        name: surname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: user successfully registered
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: something went wrong with the given data, error or the given
            email is already in use
          schema:
            type: string
        "404":
          description: something went wrong with the given data, error or the given
            email is already in use
          schema:
            type: string
        default:
          description: error in register
          schema:
            type: string
      summary: creates the user register in the db
  /userpath:
    get:
      consumes:
      - application/json
      description: get user careerpath
      produces:
      - application/json
      responses:
        "200":
          description: success show careerpath
          headers:
            Token:
              description: jwtKey
              type: string
          schema:
            type: string
        "400":
          description: missing id parameter
          schema:
            type: string
        "404":
          description: error occurred looking the path
          schema:
            type: string
        default:
          description: 'Error show user path '
          schema:
            type: string
      summary: shows a given user career path
swagger: "2.0"
